### ISSUE TITLE
In the loss, shouldn't it be  1-y_pred ? 

### ISSUE THREAD

**Issue by margokhokhlova** [umbertogriffo/focal-loss-keras#3]
I am not sure, but I think there might be an error here:   
 pt_1 = array_ops.where(y_true > 0, y_pred, tf.ones_like(y_pred))
 pt_0 =array_ops.where(y_true == 0, 1-y_pred, tf.zeros_like(y_pred))

**Comment by umbertogriffo** [comment]
Hi @margokhokhlova, I didn't get the problem you raise. Could you explain to me well?
